const root=document.documentElement,body=document.body,header=document.querySelector('[data-header]'),progress=document.querySelector('.progress span'),nav=document.querySelector('[data-nav]'),menu=document.querySelector('[data-menu-toggle]'),theme=document.querySelector('[data-theme-toggle]'),links=[...document.querySelectorAll('.nav a')];
const caseSummary=document.querySelector('.case-summary'),caseLinks=document.querySelector('.case-links'),resources=document.querySelector('.resources'),resourceGrid=resources?.querySelector('.resource-grid');
if(caseSummary&&caseLinks&&resources&&resourceGrid){const localDemo=caseLinks.querySelector('a');if(localDemo){localDemo.href='https://anranna.github.io/-/';localDemo.target='_blank';localDemo.rel='noreferrer';localDemo.innerHTML='<small>00 / DEMO</small><b>体验产品 Demo</b><span class="resource-cta">点击查看</span><i>↗</i>';resourceGrid.prepend(localDemo)}caseLinks.remove();resources.classList.add('resources-compact');const count=resources.querySelector('.resource-head small');if(count)count.textContent='PROJECT DELIVERABLES · 08 LINKS';caseSummary.append(resources)}
try{const saved=localStorage.getItem('fz-theme');if(saved==='light'||saved==='dark')root.dataset.theme=saved}catch{}
theme?.addEventListener('click',()=>{const next=root.dataset.theme==='dark'?'light':'dark';root.dataset.theme=next;try{localStorage.setItem('fz-theme',next)}catch{}});
const closeMenu=()=>{nav?.classList.remove('open');menu?.classList.remove('open');menu?.setAttribute('aria-expanded','false')};
const setActiveLink=href=>links.forEach(a=>{const active=a.getAttribute('href')===href;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});
const updateActiveLink=()=>{let current='#top',trigger=Math.min(innerHeight*.32,260);links.slice(1).forEach(a=>{const target=document.querySelector(a.getAttribute('href'));if(target&&target.getBoundingClientRect().top<=trigger)current=a.getAttribute('href')});setActiveLink(current)};
menu?.addEventListener('click',()=>{const open=nav?.classList.toggle('open');menu.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(Boolean(open)))});links.forEach(a=>a.addEventListener('click',()=>{setActiveLink(a.getAttribute('href'));closeMenu()}));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
function update(){const top=scrollY,max=document.documentElement.scrollHeight-innerHeight;header?.classList.toggle('scrolled',top>18);if(progress)progress.style.width=(max>0?top/max*100:0)+'%';updateActiveLink()}update();addEventListener('scroll',update,{passive:true});addEventListener('resize',update,{passive:true});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver'in window){body.classList.add('motion');const observer=new IntersectionObserver((entries,watch)=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');watch.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -6% 0px'});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}

